name: onboarding_kosmos
description: Onboarding package for kosmos project.
version: 1.0.0
homepage: none
publish_to: none
environment:
  sdk: '>=2.17.6 <3.0.0'
  flutter: '>=1.17.0'
dependencies:
  flutter:
    sdk: flutter
  core_kosmos:
    git:
      publish_to: none
      url: YOUR_URL
      ref: main
  ui_kosmos_v4:
    git:
      publish_to: none
      url: YOUR_URL
      ref: main
  smooth_page_indicator: ^1.0.0+2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: null
